import { Request, Response } from 'express'; import { prisma } from '../utils/prisma'; import dayjs from 'dayjs'; import { collectAuctionPrices } from '../jobs/collectAuction';
export async function triggerCollect(req: Request, res: Response): Promise<void> { const key = req.query.key as string; if (key !== process.env.JWT_SECRET) { res.status(403).json({ error: 'FORBIDDEN' }); return; } const date = (req.query.date as string) || undefined; const whsal = (req.query.whsal as string) || undefined; try { const result = await collectAuctionPrices(date, whsal); res.json({ ok: true, ...result }); } catch (e: any) { res.status(500).json({ ok: false, msg: e?.message ?? String(e) }); } }
export async function getPriceBoard(req: Request, res: Response): Promise<void> { const marketCode = (req.query.marketCode as string) || '110001'; const market = await prisma.market.findUnique({ where: { code: marketCode } }); if (!market) { res.json({ items: [], saleDate: null }); return; }
const latest = await prisma.auctionPrice.findFirst({ where: { marketId: market.id }, orderBy: { saleDate: 'desc' }, select: { saleDate: true }, }); if (!latest) { res.json({ items: [], saleDate: null }); return; } const saleDate = latest.saleDate;
const prevDateRow = await prisma.auctionPrice.findFirst({ where: { marketId: market.id, saleDate: { lt: saleDate } }, orderBy: { saleDate: 'desc' }, select: { saleDate: true }, });
const todayRows = await prisma.auctionPrice.findMany({ where: { marketId: market.id, saleDate }, include: { item: true } }); const prevRows = prevDateRow ? await prisma.auctionPrice.findMany({ where: { marketId: market.id, saleDate: prevDateRow.saleDate } }) : []; const prevByItem = new Map<number, number>(); for (const r of prevRows) prevByItem.set(r.itemId, Number(r.avgPrice));
const yearAgg = await prisma.auctionPrice.groupBy({ by: ['itemId'], where: { marketId: market.id }, _avg: { avgPrice: true } }); const yearByItem = new Map<number, number>(); for (const y of yearAgg) yearByItem.set(y.itemId, Number(y._avg.avgPrice ?? 0));
const byItem = new Map<number, any>(); for (const r of todayRows) { const ex = byItem.get(r.itemId); if (!ex || r.gradeCode === '\uC0C1') byItem.set(r.itemId, r); }
const items = [...byItem.values()].map((r) => ({ id: r.id.toString(), itemCode: r.item.itemCode, itemName: r.item.itemName, category: r.item.categoryCode, gradeCode: r.gradeCode ?? '\uC0C1', avgPrice: Number(r.avgPrice), minPrice: Number(r.minPrice), maxPrice: Number(r.maxPrice), totalQty: Number(r.totalQty), prevPrice: prevByItem.get(r.itemId) ?? Number(r.avgPrice), avgYearPrice: yearByItem.get(r.itemId) ?? Number(r.avgPrice), marketName: market.name, saleDate: dayjs(saleDate).format('YYYY-MM-DD'), }));
res.json({ items, saleDate: dayjs(saleDate).format('YYYY-MM-DD') }); }
