// ============================================================
// 개발용 목(mock) 데이터 — 백엔드 연동 전까지 사용
// ============================================================

const today = new Date().toISOString().slice(0, 10);
// Spoonacular 식재료 CDN — curl로 200 응답 확인된 파일명만 사용
const img = (name: string) =>
  `https://spoonacular.com/cdn/ingredients_250x250/${name}`;

export const MOCK_PRICES = [
  // ── 채소 (100) ──────────────────────────────
  { id: '1',  itemCode: '101',  itemName: '배추',       gradeCode: '특',  totalQty: 10, avgPrice: 2340,   minPrice: 2100,   maxPrice: 2600,   saleDate: today, marketName: '가락', prevPrice: 1978,   avgYearPrice: 2031,   category: '100', thumbnail: img('cabbage.jpg') },
  { id: '2',  itemCode: '201',  itemName: '양파',       gradeCode: '상',  totalQty: 20, avgPrice: 1560,   minPrice: 1380,   maxPrice: 1720,   saleDate: today, marketName: '가락', prevPrice: 1391,   avgYearPrice: 1440,   category: '100', thumbnail: img('white-onion.jpg') },
  { id: '3',  itemCode: '301',  itemName: '마늘',       gradeCode: '상',  totalQty: 8,  avgPrice: 8900,   minPrice: 8400,   maxPrice: 9500,   saleDate: today, marketName: '가락', prevPrice: 9197,   avgYearPrice: 9300,   category: '100', thumbnail: img('garlic.jpg') },
  { id: '4',  itemCode: '401',  itemName: '무',         gradeCode: '상',  totalQty: 20, avgPrice: 890,    minPrice: 780,    maxPrice: 1020,   saleDate: today, marketName: '가락', prevPrice: 1005,   avgYearPrice: 980,    category: '100', thumbnail: img('daikon.jpg') },
  { id: '7',  itemCode: '701',  itemName: '오이',       gradeCode: '상',  totalQty: 50, avgPrice: 2100,   minPrice: 1800,   maxPrice: 2400,   saleDate: today, marketName: '강서', prevPrice: 2050,   avgYearPrice: 1950,   category: '100', thumbnail: img('cucumber.jpg') },
  { id: '8',  itemCode: '801',  itemName: '감자',       gradeCode: '상',  totalQty: 20, avgPrice: 1450,   minPrice: 1200,   maxPrice: 1700,   saleDate: today, marketName: '강서', prevPrice: 1480,   avgYearPrice: 1500,   category: '100', thumbnail: img('new-potatoes.jpg') },
  { id: '11', itemCode: '1101', itemName: '당근',       gradeCode: '상',  totalQty: 15, avgPrice: 3100,   minPrice: 2700,   maxPrice: 3500,   saleDate: today, marketName: '가락', prevPrice: 2890,   avgYearPrice: 2950,   category: '100', thumbnail: img('carrots.jpg') },
  { id: '12', itemCode: '1201', itemName: '시금치',     gradeCode: '상',  totalQty: 5,  avgPrice: 4800,   minPrice: 4200,   maxPrice: 5400,   saleDate: today, marketName: '강서', prevPrice: 5100,   avgYearPrice: 4600,   category: '100', thumbnail: img('spinach.jpg') },
  { id: '13', itemCode: '1301', itemName: '대파',       gradeCode: '상',  totalQty: 12, avgPrice: 2650,   minPrice: 2300,   maxPrice: 3000,   saleDate: today, marketName: '가락', prevPrice: 2400,   avgYearPrice: 2500,   category: '100', thumbnail: img('spring-onions.jpg') },
  { id: '14', itemCode: '1401', itemName: '고추',       gradeCode: '상',  totalQty: 3,  avgPrice: 12500,  minPrice: 11000,  maxPrice: 14000,  saleDate: today, marketName: '가락', prevPrice: 13200,  avgYearPrice: 12800,  category: '100', thumbnail: img('red-pepper.jpg') },
  { id: '15', itemCode: '1501', itemName: '호박',       gradeCode: '상',  totalQty: 30, avgPrice: 1780,   minPrice: 1500,   maxPrice: 2100,   saleDate: today, marketName: '강서', prevPrice: 1900,   avgYearPrice: 1700,   category: '100', thumbnail: img('zucchini.jpg') },
  { id: '16', itemCode: '1601', itemName: '상추',       gradeCode: '상',  totalQty: 8,  avgPrice: 5200,   minPrice: 4500,   maxPrice: 5900,   saleDate: today, marketName: '가락', prevPrice: 4800,   avgYearPrice: 4900,   category: '100', thumbnail: img('romaine.jpg') },

  // ── 과일 (200) ──────────────────────────────
  { id: '5',  itemCode: '501',  itemName: '딸기',       gradeCode: '특',  totalQty: 2,  avgPrice: 18500,  minPrice: 16000,  maxPrice: 21000,  saleDate: today, marketName: '가락', prevPrice: 17500,  avgYearPrice: 16800,  category: '200', thumbnail: img('strawberries.jpg') },
  { id: '6',  itemCode: '601',  itemName: '사과',       gradeCode: '특',  totalQty: 10, avgPrice: 3200,   minPrice: 2800,   maxPrice: 3700,   saleDate: today, marketName: '가락', prevPrice: 3485,   avgYearPrice: 3200,   category: '200', thumbnail: img('apple.jpg') },
  { id: '17', itemCode: '1701', itemName: '배',         gradeCode: '특',  totalQty: 8,  avgPrice: 4500,   minPrice: 3900,   maxPrice: 5200,   saleDate: today, marketName: '가락', prevPrice: 4200,   avgYearPrice: 4100,   category: '200', thumbnail: img('pear.jpg') },
  { id: '18', itemCode: '1801', itemName: '감',         gradeCode: '상',  totalQty: 12, avgPrice: 2800,   minPrice: 2400,   maxPrice: 3200,   saleDate: today, marketName: '강서', prevPrice: 2950,   avgYearPrice: 2700,   category: '200', thumbnail: img('persimmon.jpg') },
  { id: '19', itemCode: '1901', itemName: '포도',       gradeCode: '특',  totalQty: 5,  avgPrice: 8900,   minPrice: 7800,   maxPrice: 10200,  saleDate: today, marketName: '가락', prevPrice: 9300,   avgYearPrice: 8500,   category: '200', thumbnail: img('red-grapes.jpg') },
  { id: '20', itemCode: '2001', itemName: '수박',       gradeCode: '상',  totalQty: 30, avgPrice: 22000,  minPrice: 18000,  maxPrice: 26000,  saleDate: today, marketName: '가락', prevPrice: 20500,  avgYearPrice: 21000,  category: '200', thumbnail: img('watermelon.jpg') },
  { id: '21', itemCode: '2101', itemName: '복숭아',     gradeCode: '상',  totalQty: 6,  avgPrice: 6500,   minPrice: 5500,   maxPrice: 7500,   saleDate: today, marketName: '강서', prevPrice: 7000,   avgYearPrice: 6200,   category: '200', thumbnail: img('peach.png') },
  { id: '22', itemCode: '2201', itemName: '참외',       gradeCode: '상',  totalQty: 10, avgPrice: 3900,   minPrice: 3300,   maxPrice: 4600,   saleDate: today, marketName: '가락', prevPrice: 4100,   avgYearPrice: 3800,   category: '200', thumbnail: img('honeydew-melon.jpg') },

  // ── 수산 (300) ──────────────────────────────
  { id: '10', itemCode: '1001', itemName: '고등어',     gradeCode: '상',  totalQty: 5,  avgPrice: 4200,   minPrice: 3600,   maxPrice: 4800,   saleDate: today, marketName: '가락', prevPrice: 4050,   avgYearPrice: 3900,   category: '300', thumbnail: img('salmon.jpg') },
  { id: '23', itemCode: '2301', itemName: '오징어',     gradeCode: '상',  totalQty: 3,  avgPrice: 6800,   minPrice: 5900,   maxPrice: 7800,   saleDate: today, marketName: '가락', prevPrice: 7200,   avgYearPrice: 6500,   category: '300', thumbnail: img('lobster.jpg') },
  { id: '24', itemCode: '2401', itemName: '갈치',       gradeCode: '상',  totalQty: 2,  avgPrice: 9500,   minPrice: 8200,   maxPrice: 11000,  saleDate: today, marketName: '가락', prevPrice: 9800,   avgYearPrice: 9000,   category: '300', thumbnail: img('fish-fillet.jpg') },
  { id: '25', itemCode: '2501', itemName: '새우',       gradeCode: '상',  totalQty: 1,  avgPrice: 38000,  minPrice: 33000,  maxPrice: 44000,  saleDate: today, marketName: '가락', prevPrice: 36000,  avgYearPrice: 35000,  category: '300', thumbnail: img('shrimp.jpg') },
  { id: '26', itemCode: '2601', itemName: '꽃게',       gradeCode: '상',  totalQty: 2,  avgPrice: 28000,  minPrice: 24000,  maxPrice: 33000,  saleDate: today, marketName: '가락', prevPrice: 31000,  avgYearPrice: 27000,  category: '300', thumbnail: img('crayfish.jpg') },
  { id: '27', itemCode: '2701', itemName: '전복',       gradeCode: '특',  totalQty: 1,  avgPrice: 52000,  minPrice: 46000,  maxPrice: 60000,  saleDate: today, marketName: '강서', prevPrice: 49000,  avgYearPrice: 50000,  category: '300', thumbnail: img('oysters.jpg') },
  { id: '28', itemCode: '2801', itemName: '참치(생)',   gradeCode: '상',  totalQty: 1,  avgPrice: 85000,  minPrice: 75000,  maxPrice: 96000,  saleDate: today, marketName: '가락', prevPrice: 82000,  avgYearPrice: 80000,  category: '300', thumbnail: img('fish-fillet.jpg') },

  // ── 축산 (400) ──────────────────────────────
  { id: '9',  itemCode: '901',  itemName: '한우(등심)', gradeCode: '1++', totalQty: 1,  avgPrice: 128000, minPrice: 112000, maxPrice: 145000, saleDate: today, marketName: '가락', prevPrice: 121000, avgYearPrice: 118000, category: '400', thumbnail: img('beef-tenderloin.jpg') },
  { id: '29', itemCode: '2901', itemName: '돼지(삼겹)', gradeCode: '1',   totalQty: 5,  avgPrice: 24000,  minPrice: 21000,  maxPrice: 27000,  saleDate: today, marketName: '가락', prevPrice: 22500,  avgYearPrice: 23000,  category: '400', thumbnail: img('pork-belly.jpg') },
  { id: '30', itemCode: '3001', itemName: '닭(육계)',   gradeCode: '상',  totalQty: 10, avgPrice: 5800,   minPrice: 5200,   maxPrice: 6500,   saleDate: today, marketName: '강서', prevPrice: 6100,   avgYearPrice: 5700,   category: '400', thumbnail: img('whole-chicken.jpg') },
  { id: '31', itemCode: '3101', itemName: '계란(30개)', gradeCode: '특',  totalQty: 50, avgPrice: 7200,   minPrice: 6500,   maxPrice: 7900,   saleDate: today, marketName: '가락', prevPrice: 6900,   avgYearPrice: 7100,   category: '400', thumbnail: img('egg.jpg') },
  { id: '32', itemCode: '3201', itemName: '한우(갈비)', gradeCode: '1+',  totalQty: 1,  avgPrice: 95000,  minPrice: 85000,  maxPrice: 108000, saleDate: today, marketName: '가락', prevPrice: 92000,  avgYearPrice: 90000,  category: '400', thumbnail: img('beef-short-ribs.jpg') },
  { id: '33', itemCode: '3301', itemName: '오리',       gradeCode: '상',  totalQty: 4,  avgPrice: 9200,   minPrice: 8100,   maxPrice: 10400,  saleDate: today, marketName: '강서', prevPrice: 9800,   avgYearPrice: 9000,   category: '400', thumbnail: img('duck-breast.jpg') },

  // ── 곡물 (500) ──────────────────────────────
  { id: '34', itemCode: '3401', itemName: '쌀(20kg)',   gradeCode: '상',  totalQty: 100, avgPrice: 58000, minPrice: 54000,  maxPrice: 62000,  saleDate: today, marketName: '가락', prevPrice: 56000,  avgYearPrice: 55000,  category: '500', thumbnail: img('black-rice.jpg') },
  { id: '35', itemCode: '3501', itemName: '콩',         gradeCode: '상',  totalQty: 8,  avgPrice: 7800,   minPrice: 7000,   maxPrice: 8700,   saleDate: today, marketName: '가락', prevPrice: 8200,   avgYearPrice: 7600,   category: '500', thumbnail: img('chickpeas.jpg') },
  { id: '36', itemCode: '3601', itemName: '고구마',     gradeCode: '상',  totalQty: 15, avgPrice: 3400,   minPrice: 2900,   maxPrice: 3900,   saleDate: today, marketName: '강서', prevPrice: 3600,   avgYearPrice: 3200,   category: '500', thumbnail: img('sweet-potato.jpg') },
  { id: '37', itemCode: '3701', itemName: '옥수수',     gradeCode: '상',  totalQty: 20, avgPrice: 1200,   minPrice: 1000,   maxPrice: 1450,   saleDate: today, marketName: '강서', prevPrice: 1100,   avgYearPrice: 1150,   category: '500', thumbnail: img('popcorn.jpg') },
  { id: '38', itemCode: '3801', itemName: '참깨',       gradeCode: '상',  totalQty: 2,  avgPrice: 18500,  minPrice: 16800,  maxPrice: 20500,  saleDate: today, marketName: '가락', prevPrice: 19200,  avgYearPrice: 18000,  category: '500', thumbnail: img('sesame-seeds.jpg') },
];

// 급등락 품목
export const MOCK_SURGE_ITEMS = [
  { name: '배추', price: 2340, changeRate: 18.3, direction: 'up' as const },
  { name: '양파', price: 1560, changeRate: 12.1, direction: 'up' as const },
  { name: '무', price: 890, changeRate: -11.4, direction: 'down' as const },
  { name: '사과', price: 3200, changeRate: -8.2, direction: 'down' as const },
];

// 시장 속보
export const MOCK_NEWS = [
  {
    id: 'n1',
    tag: '긴급',
    title: '제주 배추 냉해 피해로 공급 차질…가락 경매가 18% 급등',
    source: '농수산물 유통공사',
    time: '2시간 전',
    url: 'https://www.kamis.or.kr',
  },
  {
    id: 'n2',
    tag: '공지',
    title: '5월 가락도매시장 휴장일 안내 (어린이날 전후)',
    source: '가락시장 공식',
    time: '1일 전',
    url: 'https://www.garak.co.kr',
  },
  {
    id: 'n3',
    tag: '분석',
    title: '올봄 딸기 생산량 전년 대비 8% 증가, 가격 안정세 전망',
    source: '한국농촌경제연구원',
    time: '2일 전',
    url: 'https://www.krei.re.kr',
  },
];

// 커뮤니티 포스트
export const MOCK_POSTS = [
  {
    id: 'p1',
    title: '배추 값 폭등 언제까지? 생산자 입장에서 분석',
    content: '제주 냉해로 인해 공급이 줄면서 가격이 연일 오르고 있습니다. 현장에서 느끼는 상황과 전망을 공유드립니다. 올해처럼 이른 냉해가 오는 경우는 10년에 한 번 수준이라고 합니다.',
    authorName: '농부박씨',
    itemCode: '101',
    itemName: '배추',
    likeCount: 24,
    commentCount: 8,
    viewCount: 312,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false,
    isMyPost: false,
    liked: false,
    images: [],
    thumbnail: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    title: '수확철인데 양파 가격이 오히려 오르는 이유',
    content: '보통 수확철이면 가격이 내려가는데 올해는 특이하게 오히려 올랐습니다. 수출 증가와 작황 부진이 복합적으로 작용한 것 같습니다. 자세한 분석 올려봅니다.',
    authorName: '시세왕마니아',
    itemCode: '201',
    itemName: '양파',
    likeCount: 18,
    commentCount: 5,
    viewCount: 198,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false,
    isMyPost: false,
    liked: false,
    images: [],
    thumbnail: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    title: '수입 마늘 vs 국내산 가격 차이 직접 비교해봤습니다',
    content: '마트, 도매시장, 온라인 가격을 직접 비교해봤는데 국내산이 수입산보다 평균 40% 비쌌습니다. 그래도 맛과 향은 국내산이 훨씬 좋네요.',
    authorName: '요리연구가',
    itemCode: '301',
    itemName: '마늘',
    likeCount: 42,
    commentCount: 15,
    viewCount: 521,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    isMyPost: false,
    liked: true,
    images: [],
    thumbnail: null,
  },
  {
    id: 'p4',
    title: '설향 딸기 산지 직거래 후기 공유합니다',
    content: '마트 가격에 질려서 논산 산지 직거래를 시도해봤습니다. 2kg 한 팩에 9,000원에 구매했는데 마트 대비 거의 절반 가격이에요. 품질도 훨씬 좋았습니다.',
    authorName: '딸기러버',
    itemCode: '501',
    itemName: '딸기',
    likeCount: 67,
    commentCount: 23,
    viewCount: 842,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false,
    isMyPost: false,
    liked: false,
    images: [],
    thumbnail: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p5',
    title: '한우 등급별 시세 차이 완벽 정리 (1++/1+/1등급)',
    content: '가락시장 이번 주 경매 결과를 토대로 한우 등급별 가격을 정리했습니다. 1++ 기준 kg당 128,000원이었는데 1등급은 75,000원 수준이더군요.',
    authorName: '축산상인',
    itemCode: null,
    itemName: null,
    likeCount: 31,
    commentCount: 11,
    viewCount: 398,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false,
    isMyPost: false,
    liked: false,
    images: [],
    thumbnail: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p6',
    title: '요즘 장보기 너무 힘들어요 ㅠㅠ 가계부 절약 팁 공유해주세요',
    content: '채소값이 다 올라서 장바구니가 가벼워지네요. 예전엔 5만원이면 일주일치 장이 됐는데 요즘은 7만원이 훌쩍 넘어요. 절약 팁 아시는 분 계시면 공유 부탁드려요.',
    authorName: '주부9년차',
    itemCode: null,
    itemName: null,
    likeCount: 88,
    commentCount: 34,
    viewCount: 1203,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false,
    isMyPost: false,
    liked: false,
    images: [],
    thumbnail: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p7',
    title: '김장 배추 예약 구매 성공 후기',
    content: '10월에 미리 예약해두었더니 지금 시세 대비 40% 저렴하게 구매했습니다. 산지 직배송이라 상태도 최상이에요. 내년에도 꼭 이 방법 쓸 거예요.',
    authorName: '김장달인',
    itemCode: '101',
    itemName: '배추',
    likeCount: 55,
    commentCount: 19,
    viewCount: 634,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    isMyPost: false,
    liked: true,
    images: [],
    thumbnail: null,
  },
  {
    id: 'p8',
    title: '양파 오래 보관하는 법 총정리',
    content: '양파를 망에 달아 통풍이 잘 되는 서늘한 곳에 보관하면 3~4개월도 거뜬합니다. 냉장 보관은 오히려 더 빨리 물러지니 주의하세요.',
    authorName: '식품전문가',
    itemCode: '201',
    itemName: '양파',
    likeCount: 123,
    commentCount: 45,
    viewCount: 1872,
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false,
    isMyPost: false,
    liked: false,
    images: [],
    thumbnail: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p9',
    title: '무 가격 급락, 지금이 구매 타이밍일까요?',
    content: '무 가격이 전월 대비 11% 떨어졌습니다. 저점 매수 기회 같기도 한데, 추가 하락 가능성도 있어 보여요. 다들 어떻게 보시나요?',
    authorName: '알뜰주부',
    itemCode: '401',
    itemName: '무',
    likeCount: 29,
    commentCount: 8,
    viewCount: 287,
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false,
    isMyPost: false,
    liked: false,
    images: [],
    thumbnail: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p10',
    title: '시세왕 앱 써본 후기 (다른 앱들과 비교)',
    content: '비슷한 농산물 시세 앱들을 다 써봤는데 시세왕이 가락시장 실시간 데이터 갱신이 가장 빠르고 UI가 깔끔합니다. 앞으로도 좋은 기능 많이 추가해주세요!',
    authorName: '앱마니아',
    itemCode: null,
    itemName: null,
    likeCount: 76,
    commentCount: 28,
    viewCount: 941,
    createdAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false,
    isMyPost: false,
    liked: false,
    images: [],
    thumbnail: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p11',
    title: '마늘쫑 가격 왜 이렇게 올랐나요?',
    content: '마늘쫑 가격이 갑자기 2배 가까이 올랐는데 원인이 뭔지 아시는 분 계신가요? 중국산 수입이 줄었다는 얘기도 있던데.',
    authorName: '식당주인',
    itemCode: '301',
    itemName: '마늘',
    likeCount: 12,
    commentCount: 6,
    viewCount: 134,
    createdAt: new Date(Date.now() - 144 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false,
    isMyPost: false,
    liked: false,
    images: [],
    thumbnail: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p12',
    title: '논산 딸기 축제 현장 가격 정보 공유',
    content: '논산 딸기 축제에서 설향 2kg 한 팩을 8,000원에 구매했습니다! 마트 대비 정말 저렴해요. 5월 초까지 진행되니 관심 있으신 분들 방문해 보세요.',
    authorName: '딸기원정대',
    itemCode: '501',
    itemName: '딸기',
    likeCount: 44,
    commentCount: 17,
    viewCount: 512,
    createdAt: new Date(Date.now() - 168 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false,
    isMyPost: false,
    liked: false,
    images: [],
    thumbnail: null,
    updatedAt: new Date().toISOString(),
  },
  // 배추 추가
  {
    id: 'p13',
    title: '배추 언제 사는 게 제일 싸요? 월별 시세 패턴 정리',
    content: '3년치 가락시장 데이터를 분석해봤습니다. 배추는 봄(3~4월)과 여름(7~8월)에 고온 피해로 가격이 높고, 10월 김장철이 가장 비싼 시기입니다. 오히려 6월 수확 직후가 최저가 시즌이에요.',
    authorName: '데이터분석러',
    itemCode: '101',
    itemName: '배추',
    likeCount: 38,
    commentCount: 14,
    viewCount: 476,
    createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false, isMyPost: false, liked: false, images: [], thumbnail: null, updatedAt: new Date().toISOString(),
  },
  // 마늘 추가
  {
    id: 'p14',
    title: '마늘 냉동 보관하면 영양소 그대로일까요?',
    content: '마늘을 대량 구매해서 냉동 보관하는 분들 많으시죠? 냉동해도 알리신 성분은 거의 유지된다고 합니다. 다만 식감은 조금 물러질 수 있어요.',
    authorName: '요리연구가',
    itemCode: '301',
    itemName: '마늘',
    likeCount: 29,
    commentCount: 9,
    viewCount: 341,
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false, isMyPost: false, liked: false, images: [], thumbnail: null, updatedAt: new Date().toISOString(),
  },
  // 무 추가
  {
    id: 'p15',
    title: '가을무 vs 봄무, 맛 차이 어떤가요?',
    content: '같은 무인데 계절마다 맛이 다르더라고요. 가을무가 더 단맛이 강하고 수분도 많아서 깍두기용으로는 가을무가 최고인 것 같습니다.',
    authorName: '김치달인',
    itemCode: '401',
    itemName: '무',
    likeCount: 21,
    commentCount: 7,
    viewCount: 189,
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false, isMyPost: false, liked: false, images: [], thumbnail: null, updatedAt: new Date().toISOString(),
  },
  {
    id: 'p16',
    title: '무 3kg에 1,200원? 이번 주 가락 경매가 공유',
    content: '오늘 가락시장 경매에서 무 3kg 기준 최저가가 1,200원까지 내려갔어요. 최근 공급 과잉 영향인 것 같습니다. 저장용으로 사두기 딱 좋은 타이밍 같네요.',
    authorName: '도매상인K',
    itemCode: '401',
    itemName: '무',
    likeCount: 15,
    commentCount: 4,
    viewCount: 223,
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false, isMyPost: false, liked: false, images: [], thumbnail: null, updatedAt: new Date().toISOString(),
  },
  // 사과 추가
  {
    id: 'p17',
    title: '올해 사과 왜 이렇게 비싼가요? 원인 분석',
    content: '봄 냉해로 착과율이 평년의 60% 수준밖에 안 된다고 합니다. 10월 수확 이후에도 당분간 가격 고공행진이 이어질 것 같아요. 배 쪽은 그나마 상황이 낫다고 하네요.',
    authorName: '과수농부',
    itemCode: '601',
    itemName: '사과',
    likeCount: 47,
    commentCount: 18,
    viewCount: 634,
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false, isMyPost: false, liked: false, images: [], thumbnail: null, updatedAt: new Date().toISOString(),
  },
  {
    id: 'p18',
    title: '사과 당도 높이는 재배 꿀팁 (적과 시기)',
    content: '적과 시기를 조금 앞당기고 봉지를 씌우지 않으면 당도가 올라갑니다. 올해 시험적으로 해봤는데 당도가 14Brix까지 나왔어요. 색도 훨씬 좋아졌습니다.',
    authorName: '경북사과농장',
    itemCode: '601',
    itemName: '사과',
    likeCount: 33,
    commentCount: 11,
    viewCount: 412,
    createdAt: new Date(Date.now() - 40 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false, isMyPost: false, liked: false, images: [], thumbnail: null, updatedAt: new Date().toISOString(),
  },
  // 고등어 추가
  {
    id: 'p19',
    title: '고등어 시세가 갑자기 오른 이유 아시는 분?',
    content: '지난주 대비 고등어 경매가가 15% 올랐는데 원인을 모르겠어요. 어획량이 줄었다는 소식도 없었는데 이상하네요. 아시는 분 정보 공유 부탁드립니다.',
    authorName: '수산시장상인',
    itemCode: '1001',
    itemName: '고등어',
    likeCount: 19,
    commentCount: 8,
    viewCount: 243,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false, isMyPost: false, liked: false, images: [], thumbnail: null, updatedAt: new Date().toISOString(),
  },
  {
    id: 'p20',
    title: '고등어 제철은 언제인가요? 가격도 같이 알려주세요',
    content: '고등어는 9~11월 가을이 제철입니다. 이 시기에 지방 함량이 가장 높고 맛도 좋아요. 가격은 제철에 오히려 공급이 많아져서 봄보다 저렴한 경우가 많습니다.',
    authorName: '수산물박사',
    itemCode: '1001',
    itemName: '고등어',
    likeCount: 52,
    commentCount: 16,
    viewCount: 721,
    createdAt: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false, isMyPost: false, liked: false, images: [], thumbnail: null, updatedAt: new Date().toISOString(),
  },
  // 감자 추가
  {
    id: 'p21',
    title: '강원도 햇감자 직거래 후기',
    content: '강릉 농가에서 직접 구매했는데 10kg에 12,000원이었어요. 마트 대비 절반 가격에 신선도는 훨씬 좋았습니다. 직거래 플랫폼 추천받을 수 있을까요?',
    authorName: '직거래마니아',
    itemCode: '801',
    itemName: '감자',
    likeCount: 34,
    commentCount: 12,
    viewCount: 389,
    createdAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false, isMyPost: false, liked: false, images: [], thumbnail: null, updatedAt: new Date().toISOString(),
  },
  // 오이 추가
  {
    id: 'p22',
    title: '오이 가격 폭락 지금이 피클 만들기 최적 타이밍',
    content: '오이 kg당 600원대까지 내려왔어요. 이 기회에 피클 대량으로 만들어 두려고 합니다. 피클 레시피 공유해 주실 분 있나요?',
    authorName: '절임요리사',
    itemCode: '701',
    itemName: '오이',
    likeCount: 61,
    commentCount: 27,
    viewCount: 834,
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false, isMyPost: false, liked: false, images: [], thumbnail: null, updatedAt: new Date().toISOString(),
  },
  // 한우 추가
  {
    id: 'p23',
    title: '한우 1++ 등급 가락 경매가 역대 최고치 경신',
    content: '이번 주 한우 1++ 등급 경매가가 kg당 135,000원을 기록했습니다. 설 명절 수요가 몰리면서 역대 최고치를 경신했네요. 2월 이후에는 다소 안정될 것으로 보입니다.',
    authorName: '축산경매사',
    itemCode: '901',
    itemName: '한우(등심)',
    likeCount: 28,
    commentCount: 9,
    viewCount: 445,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    isAnonymous: false, isMyPost: false, liked: false, images: [], thumbnail: null, updatedAt: new Date().toISOString(),
  },
];

// 가격 추이 데이터 (최근 7일 기준)
export const MOCK_PRICE_HISTORY: Record<string, number[]> = {
  '배추':  [1820, 1950, 2010, 2180, 2090, 2250, 2340],
  '양파':  [1320, 1350, 1390, 1420, 1480, 1520, 1560],
  '마늘':  [9500, 9350, 9200, 9100, 9000, 8950, 8900],
  '무':    [1050, 1020, 990, 960, 930, 910, 890],
  '딸기':  [17200, 17500, 17800, 18100, 18000, 18300, 18500],
  '사과':  [3680, 3600, 3540, 3480, 3400, 3300, 3200],
  '오이':  [1980, 2020, 2050, 2080, 2070, 2090, 2100],
  '감자':  [1520, 1510, 1490, 1470, 1460, 1450, 1450],
};

// 계절 패턴 (월별 지수 0~5: 0=최저, 5=최고)
export const MOCK_SEASONAL: Record<string, number[]> = {
  '배추': [2, 1, 2, 3, 3, 0, 0, 1, 2, 3, 5, 4],
  '양파': [2, 2, 3, 4, 5, 3, 1, 0, 1, 2, 3, 3],
  '마늘': [3, 3, 4, 5, 4, 2, 1, 1, 2, 3, 3, 3],
  '무':   [2, 2, 2, 3, 2, 1, 0, 1, 2, 3, 4, 4],
  '딸기': [4, 3, 2, 1, 0, 0, 0, 1, 2, 3, 4, 5],
  '사과': [3, 2, 1, 1, 1, 0, 0, 1, 2, 4, 5, 5],
  '오이': [3, 3, 4, 4, 3, 1, 0, 1, 3, 4, 3, 3],
  '감자': [2, 2, 1, 0, 1, 3, 4, 5, 4, 2, 2, 2],
};

// 시장별 가격 비교
export const MOCK_MARKET_PRICES: Record<string, Record<string, number>> = {
  '배추': { '가락': 2340, '강서': 2180, '구리': 2100, '인천': 2050, '대전': 1980 },
  '양파': { '가락': 1560, '강서': 1480, '구리': 1440, '인천': 1390, '대전': 1350 },
  '마늘': { '가락': 8900, '강서': 8600, '구리': 8400, '인천': 8200, '대전': 8100 },
  '무':   { '가락': 890,  '강서': 850,  '구리': 830,  '인천': 810,  '대전': 790 },
  '딸기': { '가락': 18500,'강서': 17800,'구리': 17500,'인천': 17200,'대전': 16800 },
  '사과': { '가락': 3200, '강서': 3050, '구리': 2980, '인천': 2920, '대전': 2850 },
  '오이': { '가락': 2100, '강서': 2020, '구리': 1980, '인천': 1950, '대전': 1900 },
  '감자': { '가락': 1450, '강서': 1390, '구리': 1360, '인천': 1330, '대전': 1300 },
};

// AI 인사이트
export const MOCK_INSIGHTS: Record<string, string> = {
  '배추': '제주 냉해로 공급 감소 중. 3주 내 5~10% 추가 상승 가능. 구매를 서두르거나 대체재(양배추) 활용 권장.',
  '양파': '수입량 증가로 단기 안정 예상. 2~3주 내 조정 가능성이 높습니다. 관망 후 구매 추천.',
  '마늘': '수확 시즌 앞두고 완만한 하락세. 장기 보유 물량이 있다면 현재가 출하 검토 시점.',
  '무':   '공급 과잉으로 가격 급락 중. 저점 매수 기회이나 추가 하락 가능성 있으니 분할 매수 권장.',
  '딸기': '수요 강세로 당분간 강세 유지 예상. 1~2주 뒤 절정 후 조정될 가능성이 높습니다.',
  '사과': '재고 소진 중. 신과 출하까지 약 3개월 소요 예정으로 추가 하락 압력 있습니다.',
  '오이': '봄철 수요 증가와 공급 증가가 맞물려 보합세 유지 전망.',
  '감자': '작황 양호, 가격 안정세. 당분간 큰 변동 없을 것으로 예상됩니다.',
};

// 계절 분석 인사이트
export const MOCK_SEASONAL_INSIGHTS: Record<string, string> = {
  '배추': '11~1월 겨울 김장철에 가격이 최고조에 달하며, 6~8월 여름에는 공급 과잉으로 최저가를 기록합니다.',
  '양파': '4~6월 수확 직전이 성수기(최고가), 7~9월 수확 직후가 최저가입니다.',
  '마늘': '4~5월 출하 시즌 직전이 성수기. 7~8월 수확 직후에는 일시적으로 저렴합니다.',
  '무':   '10~12월 겨울무 출하 시즌에 가격이 높고, 7~8월이 최저가 시즌입니다.',
  '딸기': '11~1월이 성수기(최고가). 5~8월은 노지 딸기가 없어 가격이 매우 낮습니다.',
  '사과': '10~11월 수확기에 가격이 가장 높고, 7~8월 재고 소진기에 저렴합니다.',
  '오이': '봄·가을 재배기(3~5월, 9~11월)가 성수기. 여름과 겨울은 가격이 낮습니다.',
  '감자': '7~8월 수확 직후가 최저가. 봄철(2~4월)에 재고가 줄어들며 가격이 오릅니다.',
};

// 개발용 목 사용자 (User 타입과 일치)
export const MOCK_DEV_USER = {
  id: 1,
  uid: 'dev_user_001',
  email: 'dev@sisaewang.kr',
  nickname: 'Hun',
  userType: 'CONSUMER' as const,
  plan: 'PREMIUM' as const,
  fcmToken: null,
  isPremium: true,
  createdAt: new Date().toISOString(),
};
